# Generated by Django 5.1.6 on 2025-03-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0038_coursematerial_due_date_and_more"),
        ("web", "0038_featurevote"),
    ]

    operations = []
