# Generated by Django 5.1.6 on 2025-03-24 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0039_featurevote"),
        ("web", "0039_notehistory"),
    ]

    operations = []
